"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 11:15:51.677571
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_metadata',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('operation_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('backup_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('manifest', sa.JSON(), nullable=True),
    sa.Column('schema_version', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_runs', schema=None) as batch_op:
        batch_op.create_index('uq_backup_daily', ['local_date'], unique=True, sqlite_where=sa.text("kind = 'daily'"))

    op.create_table('export_jobs',
    sa.Column('target_key', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=True),
    sa.Column('requested_revision', sa.Integer(), nullable=False),
    sa.Column('exported_revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('target_key')
    )
    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_export_status', ['status'], unique=False)

    op.create_table('idempotency_requests',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key', 'scope')
    )
    op.create_table('import_previews',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=16), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('has_errors', sa.Boolean(), nullable=False),
    sa.Column('base_revision', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('external_key', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("kind IN ('division','team')", name='ck_org_kind'),
    sa.ForeignKeyConstraint(['parent_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index('uq_org_external_key', ['external_key'], unique=True, sqlite_where=sa.text('external_key IS NOT NULL'))

    op.create_table('tracker_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tracker_type', sa.String(length=8), nullable=False),
    sa.Column('tracker_id', sa.String(length=36), nullable=False),
    sa.Column('previous_status', sa.String(length=16), nullable=True),
    sa.Column('next_status', sa.String(length=16), nullable=False),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_task_id', sa.String(length=36), nullable=True),
    sa.Column('operation_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracker_events', schema=None) as batch_op:
        batch_op.create_index('ix_event_tracker', ['tracker_type', 'tracker_id'], unique=False)

    op.create_table('users',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('employee_number', sa.String(length=50), nullable=True),
    sa.Column('external_key', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_user_team', ['team_id'], unique=False)
        batch_op.create_index('uq_user_employee_number', ['employee_number'], unique=True, sqlite_where=sa.text('employee_number IS NOT NULL'))
        batch_op.create_index('uq_user_external_key', ['external_key'], unique=True, sqlite_where=sa.text('external_key IS NOT NULL'))

    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('is_short_term', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('background_doc', sa.JSON(), nullable=True),
    sa.Column('purpose_doc', sa.JSON(), nullable=True),
    sa.Column('retrospective_doc', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('preparing','in_progress','on_hold','completed','cancelled')", name='ck_project_status'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_project_team', ['team_id'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_relative_path', sa.String(length=300), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("state IN ('temp','committed')", name='ck_att_state'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_logs',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('author_snapshot', sa.JSON(), nullable=True),
    sa.Column('lesson_doc', sa.JSON(), nullable=True),
    sa.Column('note_doc', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'author_id', 'work_date', name='uq_log_project_author_date')
    )
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.create_index('ix_log_project_date', ['project_id', 'work_date'], unique=False)

    op.create_table('issues',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('content_doc', sa.JSON(), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('impact_doc', sa.JSON(), nullable=True),
    sa.Column('response_doc', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_log_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('open','in_progress','resolved','closed')", name='ck_issue_status'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index('ix_issue_project', ['project_id'], unique=False)

    op.create_table('milestones',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description_doc', sa.JSON(), nullable=True),
    sa.Column('is_general', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_end', sa.Date(), nullable=True),
    sa.Column('baseline_start', sa.Date(), nullable=True),
    sa.Column('baseline_end', sa.Date(), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_end', sa.Date(), nullable=True),
    sa.Column('baseline_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('planned','in_progress','on_hold','completed','cancelled')", name='ck_ms_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index('ix_milestone_project', ['project_id'], unique=False)
        batch_op.create_index('uq_milestone_general', ['project_id'], unique=True, sqlite_where=sa.text('is_general IS 1'))

    op.create_table('project_kpis',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('baseline_value', sa.String(length=50), nullable=True),
    sa.Column('target_value', sa.String(length=50), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("direction IS NULL OR direction IN ('increase','decrease','target')", name='ck_kpi_dir'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_kpis', schema=None) as batch_op:
        batch_op.create_index('ix_kpi_project', ['project_id'], unique=False)

    op.create_table('project_members',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('todos',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('content_doc', sa.JSON(), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_log_id', sa.String(length=36), nullable=True),
    sa.Column('source_issue_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('open','in_progress','completed','cancelled')", name='ck_todo_status'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index('ix_todo_project', ['project_id'], unique=False)

    op.create_table('achievements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('preset_key', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content_doc', sa.JSON(), nullable=True),
    sa.Column('numeric_payload', sa.JSON(), nullable=True),
    sa.Column('kpi_id', sa.String(length=36), nullable=True),
    sa.Column('kpi_snapshot', sa.JSON(), nullable=True),
    sa.Column('measured_on', sa.Date(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('source_task_id', sa.String(length=36), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("type IN ('quantitative','qualitative')", name='ck_ach_type'),
    sa.ForeignKeyConstraint(['kpi_id'], ['project_kpis.id'], ),
    sa.ForeignKeyConstraint(['log_id'], ['daily_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index('ix_ach_log', ['log_id'], unique=False)

    op.create_table('log_collaborators',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name_snapshot', sa.String(length=100), nullable=False),
    sa.Column('team_snapshot', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['daily_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('log_id', 'user_id')
    )
    op.create_table('log_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('milestone_id', sa.String(length=36), nullable=True),
    sa.Column('milestone_snapshot', sa.JSON(), nullable=True),
    sa.Column('content_doc', sa.JSON(), nullable=False),
    sa.Column('performed_start', sa.Date(), nullable=True),
    sa.Column('performed_end', sa.Date(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('source_event_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['daily_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_task_log', ['log_id'], unique=False)

    op.create_table('log_tracker_refs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('client_entry_id', sa.String(length=64), nullable=False),
    sa.Column('tracker_type', sa.String(length=8), nullable=False),
    sa.Column('tracker_id', sa.String(length=36), nullable=False),
    sa.Column('original_snapshot', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('hidden_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("tracker_type IN ('todo','issue')", name='ck_ref_type'),
    sa.ForeignKeyConstraint(['log_id'], ['daily_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_id', 'client_entry_id', name='uq_ref_log_client_entry')
    )
    op.create_table('task_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('attachment_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['log_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_attachments', schema=None) as batch_op:
        batch_op.create_index('ix_taskatt_att', ['attachment_id'], unique=False)
        batch_op.create_index('ix_taskatt_task', ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_attachments', schema=None) as batch_op:
        batch_op.drop_index('ix_taskatt_task')
        batch_op.drop_index('ix_taskatt_att')

    op.drop_table('task_attachments')
    op.drop_table('log_tracker_refs')
    with op.batch_alter_table('log_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_task_log')

    op.drop_table('log_tasks')
    op.drop_table('log_collaborators')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index('ix_ach_log')

    op.drop_table('achievements')
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index('ix_todo_project')

    op.drop_table('todos')
    op.drop_table('project_members')
    with op.batch_alter_table('project_kpis', schema=None) as batch_op:
        batch_op.drop_index('ix_kpi_project')

    op.drop_table('project_kpis')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index('uq_milestone_general', sqlite_where=sa.text('is_general IS 1'))
        batch_op.drop_index('ix_milestone_project')

    op.drop_table('milestones')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index('ix_issue_project')

    op.drop_table('issues')
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_log_project_date')

    op.drop_table('daily_logs')
    op.drop_table('attachments')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_project_team')

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('uq_user_external_key', sqlite_where=sa.text('external_key IS NOT NULL'))
        batch_op.drop_index('uq_user_employee_number', sqlite_where=sa.text('employee_number IS NOT NULL'))
        batch_op.drop_index('ix_user_team')

    op.drop_table('users')
    with op.batch_alter_table('tracker_events', schema=None) as batch_op:
        batch_op.drop_index('ix_event_tracker')

    op.drop_table('tracker_events')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index('uq_org_external_key', sqlite_where=sa.text('external_key IS NOT NULL'))

    op.drop_table('organizations')
    op.drop_table('import_previews')
    op.drop_table('idempotency_requests')
    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_export_status')

    op.drop_table('export_jobs')
    with op.batch_alter_table('backup_runs', schema=None) as batch_op:
        batch_op.drop_index('uq_backup_daily', sqlite_where=sa.text("kind = 'daily'"))

    op.drop_table('backup_runs')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_entity')

    op.drop_table('audit_events')
    op.drop_table('app_metadata')
    # ### end Alembic commands ###
