"""THIRD_PARTY_NOTICES.md 생성: 서버 런타임(Python)과 화면 번들(npm production)의 라이선스 목록.

  python scripts/gen_notices.py     (개발 PC: Python 환경 + frontend/node_modules 필요)

라이선스는 각 패키지가 선언한 메타데이터를 그대로 옮긴다. 자동 판정이 아니므로 배포 전에 법무/라이선스 검토를 거쳐야 한다.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from importlib import metadata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def py_rows() -> list[tuple[str, str, str, str]]:
    names = [ln.split("==")[0] for ln in (ROOT / "backend" / "requirements.txt").read_text(encoding="utf-8").splitlines()
             if "==" in ln and not ln.startswith("#")]
    rows = []
    for n in sorted(names, key=str.lower):
        d = metadata.distribution(n)
        m = d.metadata
        lic = m.get("License-Expression") or ""
        if not lic:
            lic = (m.get("License") or "").strip().splitlines()[0][:60] if m.get("License") else ""
        if not lic or len(lic) > 60:
            cls = [c.split("::")[-1].strip() for c in (m.get_all("Classifier") or []) if c.startswith("License ::")]
            lic = ", ".join(cls) or lic or "(not declared)"
        home = m.get("Home-page") or next((u.split(",", 1)[1].strip() for u in (m.get_all("Project-URL") or []) if "," in u), "")
        rows.append((m["Name"], d.version, lic, home))
    return rows


def npm_rows() -> list[tuple[str, str, str, str]]:
    fe = ROOT / "frontend"
    out = subprocess.run(["npm", "ls", "--omit=dev", "--all", "--parseable"], cwd=fe, capture_output=True, text=True, shell=(sys.platform == "win32"))
    rows, seen = [], set()
    for line in out.stdout.splitlines():
        p = Path(line.strip())
        pj = p / "package.json"
        if not pj.exists() or p == fe:
            continue
        j = json.loads(pj.read_text(encoding="utf-8"))
        key = (j["name"], j["version"])
        if key in seen:
            continue
        seen.add(key)
        lic = j.get("license") or "; ".join(x.get("type", "") for x in j.get("licenses", [])) or "(not declared)"
        repo = j.get("repository")
        url = (repo.get("url") if isinstance(repo, dict) else repo) or j.get("homepage", "")
        rows.append((j["name"], j["version"], str(lic), re.sub(r"^git\+", "", str(url))))
    return sorted(rows, key=lambda r: r[0].lower())


def table(rows) -> str:
    return "| Package | Version | License (as declared) | Source |\n|---|---|---|---|\n" + "\n".join(
        f"| {n} | {v} | {l} | {u} |" for n, v, l, u in rows)


def main() -> None:
    frappe = (ROOT / "frontend" / "src" / "vendor" / "frappe-gantt.LICENSE.txt").read_text(encoding="utf-8").strip()
    text = f"""# Third-party notices

Generated by `scripts/gen_notices.py`. License names are copied from each package's own metadata (not independently verified);
get a license review before external distribution. Worklog itself has no license file yet (internal tool).

## Server runtime (Python, `backend/requirements.txt`)

{table(py_rows())}

## Browser bundle (npm production dependencies of `frontend/`)

{table(npm_rows())}

Notes
- Tiptap (`@tiptap/*`) is used under its open-source MIT license only. No paid/cloud Tiptap features are used.
- Frappe Gantt `dist/frappe-gantt.css` is copied to `frontend/src/vendor/` because the package `exports` field does not expose it.
- Development-only tools (vite, vitest, typescript, pytest, ...) are not shipped to the operating PC.

## Bundled report assets (`backend/weekly_report`, `backend/report_assets`)

- `backend/weekly_report/` is an internal package copied from the in-house `weekly-report` project (PPT generator). Local changes are listed in `backend/weekly_report/VENDORED.md`.
- PPT templates (`report_assets/templates/*.pptx`) are company report formats.
- `report_assets/fonts/LGSM*.TTF` (LG Smart font) are company fonts marked "All rights reserved". They are used only to measure text width
  and are not embedded in generated PPT files. Remove the folder before distributing outside the company; the generator then falls back to a
  conservative width estimate.

## Frappe Gantt license text

```
{frappe}
```
"""
    (ROOT / "THIRD_PARTY_NOTICES.md").write_text(text, encoding="utf-8")
    print("written THIRD_PARTY_NOTICES.md")


if __name__ == "__main__":
    main()
