"""설치된 환경에서 런타임/개발 의존성의 정확한 버전 고정 파일을 생성한다.

  python scripts/gen_requirements.py

backend/requirements.txt      : 서버 실행에 필요한 패키지 전체(직접+전이) 정확한 버전
backend/requirements-dev.txt  : 테스트용 추가 패키지(런타임 포함)
직접 의존성 목록을 바꾸면 이 스크립트를 다시 실행하고 THIRD_PARTY_NOTICES.md 도 갱신한다(scripts/gen_notices.py).
"""
from __future__ import annotations

import re
import sys
from importlib import metadata
from pathlib import Path

# colorama: click (uvicorn) uses it for console colors on Windows although click's metadata does not declare it.
RUNTIME = ["fastapi", "uvicorn", "sqlalchemy", "alembic", "pydantic", "openpyxl", "pillow", "python-multipart", "tzdata", "colorama",
           "python-pptx", "jsonschema", "fonttools"]  # 마지막 셋: 보고자료(PPT) 생성 (backend/weekly_report)
DEV = ["pytest", "httpx"]


def norm(n: str) -> str:
    return re.sub(r"[-_.]+", "-", n).lower()


def closure(roots: list[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    todo = [norm(r) for r in roots]
    while todo:
        name = todo.pop()
        if name in out:
            continue
        try:
            dist = metadata.distribution(name)
        except metadata.PackageNotFoundError:
            continue
        out[name] = dist.version
        for req in dist.requires or []:
            if "extra ==" in req:  # 선택 extra 는 제외
                continue
            marker = req.split(";", 1)[1] if ";" in req else ""
            if "win32" in marker and sys.platform != "win32":
                continue
            todo.append(norm(re.split(r"[ ;<>=!~\[(]", req.strip(), 1)[0]))
    return out


def main() -> None:
    root = Path(__file__).resolve().parents[1] / "backend"
    runtime = closure(RUNTIME)
    dev = {k: v for k, v in closure(RUNTIME + DEV).items() if k not in runtime}
    # ASCII only: pip may decode requirement files with the system codepage (cp949 on Korean Windows).
    header = f"# generated by scripts/gen_requirements.py - exact versions verified on Python {sys.version.split()[0]} / {sys.platform}\n"
    (root / "requirements.txt").write_text(header + "\n".join(f"{k}=={v}" for k, v in sorted(runtime.items())) + "\n", encoding="utf-8")
    (root / "requirements-dev.txt").write_text(
        header + "-r requirements.txt\n" + "\n".join(f"{k}=={v}" for k, v in sorted(dev.items())) + "\n", encoding="utf-8")
    print(f"runtime {len(runtime)} packages, dev-only {len(dev)} packages")


if __name__ == "__main__":
    main()
